#!/usr/bin/env node
// scripts/build.js — Dnuzi AI build script
// Assembles lib/index.cjs and lib/index.mjs from src/
"use strict";

const fs   = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SRC  = path.join(ROOT, "src");
const LIB  = path.join(ROOT, "lib");

// ── ensure lib/ exists ──────────────────────────────────────────────────────
if (!fs.existsSync(LIB)) fs.mkdirSync(LIB, { recursive: true });

// ── read src files ──────────────────────────────────────────────────────────
const client  = fs.readFileSync(path.join(SRC, "client.js"),  "utf8");
const storage = fs.readFileSync(path.join(SRC, "storage.js"), "utf8");

// ── build index.cjs (CommonJS bundle) ───────────────────────────────────────
const cjs = `// lib/index.cjs — Dnuzi AI SDK  (CommonJS — auto-generated by scripts/build.js)
"use strict";

// ─── client.js ───────────────────────────────────────────────────────────────
${client.replace(/^module\.exports.*$/m, "").trim()}

// ─── storage.js ──────────────────────────────────────────────────────────────
${storage.replace(/^module\.exports.*$/m, "").trim()}

// ─── DnuziAI high-level class ────────────────────────────────────────────────
/**
 * DnuziAI — high-level SDK combining the API client + optional DB storage.
 *
 * Quick start:
 *   const { DnuziAI } = require("dnuzi");
 *   const ai = new DnuziAI();
 *   const { result } = await ai.chat("Hello!");
 *   console.log(result);
 *
 * With MongoDB storage:
 *   const ai = new DnuziAI({ userId: "alice" });
 *   await ai.enableStorage();
 *   const { result } = await ai.chat("Hello!");
 */
class DnuziAI {
  constructor(options = {}) {
    this.client  = new DnuziClient(options);
    this.storage = new DnuziStorage(options.userId || "anonymous");
  }

  /** Enable persistent MongoDB storage */
  async enableStorage(userId) {
    await this.storage.connect(userId);
    return this;
  }

  /** Send a message; auto-persists if storage is enabled */
  async chat(message) {
    const response = await this.client.chat(message);
    if (this.storage.enabled) {
      await this.storage.saveTurn({
        conversationId:   response.conversationId,
        userMessage:      message,
        assistantMessage: response.result,
        responseTime:     response.responseTime,
      });
    }
    return response;
  }

  /** Alias */
  async ask(message) { return this.chat(message); }

  /** Start a fresh conversation thread */
  newConversation() { this.client.newConversation(); }

  /** In-memory history for the current session */
  getHistory() { return this.client.getHistory(); }

  /** Persistent history from MongoDB (requires enableStorage) */
  async getPersistentHistory(conversationId) {
    return this.storage.getConversation(conversationId || this.client.conversationId);
  }

  /** List all stored conversation IDs */
  async listConversations() { return this.storage.listConversations(); }

  /** Delete a stored conversation */
  async deleteConversation(id) { return this.storage.deleteConversation(id); }

  /** Get usage stats from MongoDB */
  async getStats() { return this.storage.getStats(); }

  /** Set/get user preferences in MongoDB */
  async setPref(k, v) { return this.storage.setPref(k, v); }
  async getPref(k, def) { return this.storage.getPref(k, def); }

  /** Gracefully close MongoDB connection */
  async close() { await this.storage.disconnect(); }
}

module.exports = { DnuziAI, DnuziClient, DnuziStorage };
`;

// ── build index.mjs (ESM wrapper) ───────────────────────────────────────────
const mjs = `// lib/index.mjs — Dnuzi AI SDK  (ESM — auto-generated by scripts/build.js)
import cjs from "./index.cjs";
export const { DnuziAI, DnuziClient, DnuziStorage } = cjs;
export default cjs.DnuziAI;
`;

fs.writeFileSync(path.join(LIB, "index.cjs"), cjs, "utf8");
fs.writeFileSync(path.join(LIB, "index.mjs"), mjs, "utf8");

console.log("✓  Built lib/index.cjs");
console.log("✓  Built lib/index.mjs");
